from pathlib import Path
import base64, json
ROOT=Path(__file__).parent
img_files=[ROOT/f'scene_0{i}_{name}.jpg' for i,name in enumerate(['climate_bridge','timeline','clean_project','emission_baseline','verification_registry','climate_question'],1)]
imgs=[]
for p in img_files:
    imgs.append('data:image/jpeg;base64,'+base64.b64encode(p.read_bytes()).decode())
audio=[]
for p in [ROOT/'narration_01.mp3',ROOT/'narration_02.mp3']:
    audio.append('data:audio/mpeg;base64,'+base64.b64encode(p.read_bytes()).decode())
scenes=[
 {'f':0,'k':'INDIA–JAPAN JCM','h':'CREDIT KISE MILEGA?','s':'Kya ek emission cut do baar count ho sakta hai?','source':''},
 {'f':1,'k':'THE MECHANISM','h':'ARTICLE 6.2','s':'Investment + clean technology + verified cuts','source':'PIB · MoC 2025'},
 {'f':2,'k':'HOW A CREDIT STARTS','h':'REFERENCE − PROJECT','s':'A conservative baseline meets real project data','source':'MoEFCC · Rules of Implementation'},
 {'f':3,'k':'BEFORE CREDIT','h':'VERIFY BEFORE YOU TRADE','s':'Joint Committee + third-party verification','source':'MoEFCC · Rules of Implementation'},
 {'f':4,'k':'THE ACCOUNTING GUARDRAIL','h':'NO DOUBLE COUNTING','s':'Two registries. Corresponding adjustments.','source':'MoEFCC · Rules of Implementation'},
 {'f':5,'k':'THE BIG QUESTION','h':'REAL PROJECTS. REAL DATA.','s':'Climate finance or carbon accounting risk?','source':''},
]
T='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>India Japan JCM Short Preview</title><style>
:root{--ivory:#fffaf0;--ink:#101a3a;--indigo:#2437a8;--cyan:#10bfe8;--gold:#f0ad24;--saffron:#ed6b2f;--mint:#1aa78a}*{box-sizing:border-box}html,body{margin:0;background:#e6ebf6;color:var(--ink);font-family:Arial,Helvetica,sans-serif}body{min-height:100vh;display:grid;place-items:center;padding:12px}.wrap{width:min(540px,100vw - 18px)}.stage{position:relative;aspect-ratio:9/16;overflow:hidden;border-radius:16px;background:var(--ivory);box-shadow:0 18px 55px rgba(20,34,74,.25)}.bg{position:absolute;inset:0;background-size:cover;background-position:center;opacity:0;transform:scale(1.06);transition:opacity .55s ease,transform 1s cubic-bezier(.2,.8,.2,1)}.bg.show{opacity:1;transform:scale(1)}.bg:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(255,250,240,.15),rgba(16,26,58,.06) 24%,rgba(16,26,58,.88) 78%,rgba(16,26,58,.96))}.top{position:absolute;z-index:4;top:4%;left:7%;right:7%;display:flex;justify-content:space-between;color:white;font-size:11px;font-weight:900;letter-spacing:.12em;text-shadow:0 1px 4px #101a3a}.brand{display:flex;align-items:center;gap:6px}.dot{width:8px;height:8px;border-radius:50%;background:linear-gradient(135deg,var(--gold),var(--cyan))}.copy{position:absolute;z-index:4;left:7%;right:7%;bottom:18%;color:white}.kicker{display:inline-flex;align-items:center;gap:7px;color:#ffd35b;font-size:12px;font-weight:900;letter-spacing:.12em}.kicker:before{content:"";width:25px;height:3px;background:var(--cyan)}h1{font-size:clamp(32px,7vw,53px);line-height:.98;margin:13px 0 10px;color:#fff;letter-spacing:-.05em;text-shadow:0 2px 5px rgba(0,0,0,.35)}.sub{font-size:18px;line-height:1.16;font-weight:800;color:#e3faff;max-width:440px}.source{display:none;margin-top:14px;padding:8px 10px;border-left:3px solid var(--gold);background:rgba(16,26,58,.76);font-size:10px;line-height:1.2;font-weight:800;color:#fff}.source.on{display:block}.ai{position:absolute;z-index:5;right:7%;bottom:7%;font-size:9px;font-weight:900;letter-spacing:.08em;padding:6px 8px;border-radius:4px;background:rgba(16,26,58,.78);color:#fff}.caption{position:absolute;z-index:5;left:7%;right:7%;bottom:11%;height:4px;border-radius:99px;background:rgba(255,255,255,.30);overflow:hidden}.caption i{display:block;height:100%;width:0;background:linear-gradient(90deg,var(--saffron),var(--gold),var(--cyan));border-radius:99px}.controls{display:flex;align-items:center;gap:8px;margin-top:10px}.button{border:0;border-radius:8px;background:var(--indigo);color:white;padding:9px 12px;font-weight:900;cursor:pointer}.bar{height:7px;flex:1;background:#c9d4e8;border-radius:99px;overflow:hidden}.fill{height:100%;width:0;background:linear-gradient(90deg,var(--saffron),var(--gold),var(--cyan))}.time{font-size:11px;font-weight:900;color:#536080;min-width:50px;text-align:right}.note{margin-top:8px;color:#536080;font-size:11px;font-weight:700}.enter{animation:enter .55s ease}@keyframes enter{from{opacity:.1;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
</style></head><body><main class="wrap"><section class="stage"><div class="bg" id="bgA"></div><div class="bg" id="bgB"></div><div class="top"><div class="brand"><span class="dot"></span>BENAQAAB INDIA</div><div id="sceneNo">01 / 06</div></div><div class="copy"><div class="kicker" id="kicker"></div><h1 id="headline"></h1><div class="sub" id="sub"></div><div class="source" id="source"></div></div><div class="ai">AI ILLUSTRATIVE VISUAL</div><div class="caption"><i id="capFill"></i></div></section><div class="controls"><button class="button" id="play">Play Short preview</button><div class="bar"><div class="fill" id="fill"></div></div><div class="time" id="time">0:00</div></div><div class="note">Vertical 1080×1920 preview · narration is real voice audio · MP4 rendering remains gated until approval.</div><audio id="a1" preload="auto" src="__A1__"></audio><audio id="a2" preload="auto" src="__A2__"></audio></main><script>
const imgs=__IMGS__,scenes=__SCENES__,a1=document.getElementById('a1'),a2=document.getElementById('a2'),play=document.getElementById('play'),bgA=document.getElementById('bgA'),bgB=document.getElementById('bgB'),kicker=document.getElementById('kicker'),headline=document.getElementById('headline'),sub=document.getElementById('sub'),source=document.getElementById('source'),sceneNo=document.getElementById('sceneNo'),fill=document.getElementById('fill'),capFill=document.getElementById('capFill'),time=document.getElementById('time');let current=-1,active='a',d1=84,d2=34,total=118;
const fractions=[0,.10,.23,.39,.56,.76,1];function fmt(t){t=Math.max(0,Math.floor(t));return Math.floor(t/60)+':'+String(t%60).padStart(2,'0')}function globalTime(){return a1.ended?d1+a2.currentTime:a1.currentTime}function render(t){if(!d1||!d2)return;let i=0;for(let n=0;n<scenes.length;n++){if(t>=fractions[n]*total)i=n}if(i!==current){current=i;const s=scenes[i],incoming=active==='a'?bgB:bgA,outgoing=active==='a'?bgA:bgB;incoming.style.backgroundImage='url("'+imgs[s.f]+'")';incoming.classList.remove('show');void incoming.offsetWidth;incoming.classList.add('show');outgoing.classList.remove('show');active=active==='a'?'b':'a';kicker.textContent=s.k;headline.textContent=s.h;sub.textContent=s.s;sceneNo.textContent=String(i+1).padStart(2,'0')+' / '+scenes.length;if(s.source){source.textContent=s.source;source.classList.add('on')}else source.classList.remove('on');[kicker,headline,sub,source].forEach(x=>{x.classList.remove('enter');void x.offsetWidth;x.classList.add('enter')})}fill.style.width=Math.min(100,t/total*100)+'%';capFill.style.width=Math.min(100,((t-fractions[current]*total)/((fractions[current+1]-fractions[current])*total))*100)+'%';time.textContent=fmt(t)}function tick(){render(globalTime());if(!a1.paused||!a2.paused)requestAnimationFrame(tick)}a1.addEventListener('loadedmetadata',()=>{if(Number.isFinite(a1.duration)&&a1.duration>0){d1=a1.duration;total=d1+d2;}});a2.addEventListener('loadedmetadata',()=>{if(Number.isFinite(a2.duration)&&a2.duration>0){d2=a2.duration;total=d1+d2;}});a1.addEventListener('timeupdate',()=>render(globalTime()));a2.addEventListener('timeupdate',()=>render(globalTime()));a1.addEventListener('ended',()=>{a2.play().catch(()=>{play.textContent='Audio blocked; visual preview loaded'});});a2.addEventListener('ended',()=>{play.textContent='Replay Short preview';render(total)});a1.addEventListener('error',()=>{play.textContent='Audio unavailable; visual preview loaded'});a2.addEventListener('error',()=>{play.textContent='Audio unavailable; visual preview loaded'});play.addEventListener('click',()=>{if(a1.paused&&a2.paused){if(a1.ended){a1.currentTime=0;a2.currentTime=0}a1.play().then(()=>{play.textContent='Pause preview';tick()}).catch(()=>{play.textContent='Audio unavailable; visual preview loaded'})}else{a1.pause();a2.pause();play.textContent='Play Short preview'}});a1.addEventListener('pause',()=>{if(!a2.ended)play.textContent='Play Short preview'});a2.addEventListener('pause',()=>{if(!a2.ended)play.textContent='Play Short preview'});render(0);
</script></body></html>'''
html=T.replace('__IMGS__',json.dumps(imgs)).replace('__SCENES__',json.dumps(scenes,ensure_ascii=False)).replace('__A1__',audio[0]).replace('__A2__',audio[1])
(ROOT/'comp.html').write_text(html,encoding='utf-8')
print('wrote',ROOT/'comp.html',len(html))
