from pathlib import Path
import json,re,base64
R=Path(__file__).parent
# Preserve the prior preview as a local revision; no remote repository edits.
p=R/'preview.html';html=p.read_text();(R/'preview_before_repo.html').write_text(html)
m=re.search(r'const scenes=(.*?),duration=',html);S=json.loads(m.group(1));T=json.loads((R/'timing_repo.json').read_text());D=T['duration']
starts=[0,7.70,16.22,22.58,33.86,42.4,52.4]
heads=['DUNIYA MEIN<br><em>KYA BADLA?</em>','SPY CHIEF<br><em>UNDER INVESTIGATION</em>','BETTER SCHOOLS.<br><em>MORE TEACHERS.</em>','EBOLA CASE.<br><em>CONTACT TRACING.</em>','ELECTION WIN.<br><em>NO MAJORITY.</em>','GHOST PARTICLES.<br><em>PHYSICS NOBEL.</em>','SHOR NAHI.<br><em>SOURCE KE SAATH.</em>']
subs=['Germany se Nobel tak — five developments.','Allegations are not a conviction.','Students, teachers and parents protest.','Imported case ≠ nationwide spread.','Victory is not an independence vote.','Francis Halzen · IceCube observatory.','Like ★  /  Subscribe ▶']
rails=[['WORLD','CONTEXT','SOURCES'],['ALLEGATION','INQUIRY','NOT GUILT'],['STAFFING','SCHOOLS','DEMANDS'],['CASE','CONTACTS','MONITOR'],['ELECTION','MINORITY','NO SECESSION'],['NEUTRINOS','ICECUBE','DISCOVERY'],['SACH','SABOOT','BEBAK']]
for i,s in enumerate(S):s.update(t=starts[i],h=heads[i],sub=subs[i],rail=rails[i])
logo=base64.b64encode((R/'repo_reference/brand/logo.png').read_bytes()).decode();html=re.sub(r'<div class="brand">.*?</div>',f'<div class="brand"><img src="data:image/png;base64,{logo}" alt="Benaqaab India official logo"></div>',html,count=1)
fonts=''
for name,file in [('Anton','Anton.ttf'),('Inter','Inter.ttf')]:
 b=base64.b64encode((R/'repo_reference/brand/fonts'/file).read_bytes()).decode();fonts+=f'@font-face{{font-family:{name};src:url(data:font/ttf;base64,{b}) format("truetype");font-display:block;}}'
css='''body{font-family:Inter,Arial,sans-serif}.brand{top:3%;left:6%;width:14%;height:auto;display:block}.brand img{display:block;width:100%;height:auto;object-fit:contain;filter:none}.date{top:5.5%;right:7%;font-size:2.2cqw}.line{top:12%;opacity:.5}.photo-main{top:13%;height:49%;left:1%;width:98%;will-change:transform}.ai-main{will-change:transform}.copy{top:70%;left:7%;right:7%}.kicker{font-size:2.2cqw;letter-spacing:.09em}h1{font-family:Anton,Arial,sans-serif;font-weight:400;font-size:7.1cqw;letter-spacing:0;line-height:1.04;margin:7px 0 6px}.sub{font-size:3.0cqw;line-height:1.28;font-weight:650}.credit{top:85%;bottom:auto;font-size:1.9cqw;border:0;padding-left:0}.label{display:none}.image-note{top:60%;background:transparent;padding:0;left:7%;right:7%;font-size:2.1cqw;text-shadow:0 1px 4px #000,0 1px 7px #000;line-height:1.3}.mechanism{position:absolute;top:63%;left:7%;width:86%;height:5%;z-index:4}.mechanism svg{width:100%;height:100%;overflow:visible}.track{display:none}.enter,.photo-in{animation:none!important}.grain{opacity:.4}.phone{border-radius:9px}.repo-status{font-size:11px;color:#e7b389;line-height:1.55}.shade{background:linear-gradient(180deg,#07140dc2 0%,transparent 22%,transparent 40%,#091c1340 55%,#091c13b0 65%,#091c13eb 80%,#091c13 100%)}
'''
html=html.replace('</style>',fonts+css+'</style>')
html=html.replace('<div class="copy">','<div class="mechanism" id="mechanism"></div><div class="copy">',1)
html=html.replace('Temporary text branding: the original logo was deleted.','Original logo and embedded typography restored from your repository.')
html=html.replace('Five stories in a one-minute Hinglish preview.','Five stories in a question-led Hinglish preview.')
html=html.replace('PREVIEW ONLY · Final export awaits approval.','REPOSITORY-ALIGNED PREVIEW · Final export awaits approval.')
html=re.sub(r'<audio id="audio".*?</audio>', '<audio id="audio" preload="auto" src="data:audio/mpeg;base64,'+base64.b64encode((R/'narration_repo.mp3').read_bytes()).decode()+'"></audio>',html)
html=re.sub(r'max="60\.52"',f'max="{D}"',html)
script='''
const scenes=__SCENES__,duration=__DURATION__,audio=document.getElementById('audio');const $=id=>document.getElementById(id);let current=-1,visualKey='';
function fmt(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
scenes.forEach((s,i)=>{const b=document.createElement('button');b.className='chapter';b.innerHTML=s.k.split(' / ')[0]+'<span>'+fmt(s.t)+'</span>';b.onclick=()=>{audio.currentTime=s.t;render(s.t)};$('chapters').appendChild(b)});
function photoFor(t,n){let s=scenes[n],end=n+1<scenes.length?scenes[n+1].t:duration;return s.visuals.length>1&&t>=(s.t+end)/2?1:0}
function updateVisual(t,n){let s=scenes[n],vindex=photoFor(t,n),key=n+'-'+vindex;if(key===visualKey)return;visualKey=key;let v=s.visuals[vindex];$('art').innerHTML=(v.ai?'':'<img class="photo-wash" alt="" src="'+v.image+'">')+'<img class="'+(v.ai?'ai-main':'photo-main')+'" alt="'+v.label+'" src="'+v.image+'"><div class="shade"></div><div class="image-note">'+v.label+'</div>';const box=$('sourceLink');box.replaceChildren();function link(text,url){let a=document.createElement('a');a.textContent=text;a.href=url;a.target='_blank';a.rel='noopener';box.appendChild(a)}if(s.url)link(s.src,s.url);else box.appendChild(document.createTextNode('Dated world-news snapshot.'));let small=document.createElement('small');small.textContent=v.label+' — '+v.credit;box.appendChild(small);if(v.source){link('Photo source',v.source);box.appendChild(document.createTextNode(' · '));if(v.licurl)link(v.license,v.licurl);else box.appendChild(document.createTextNode(v.license));}}
function mechanism(t,n){let a=scenes[n].rail,u=t-scenes[n].t,end=(n+1<scenes.length?scenes[n+1].t:duration)-scenes[n].t,p=Math.min(.999,u/end),active=Math.floor(p*3);let body='<svg viewBox="0 0 360 44" xmlns="http://www.w3.org/2000/svg"><path d="M24 12H336" stroke="#a5b4a6" stroke-opacity=".35" stroke-width="1.5"/><path d="M24 12H'+(24+312*p)+'" stroke="#efaa6d" stroke-width="2"/>';
for(let j=0;j<3;j++){let x=24+j*156;body+='<circle cx="'+x+'" cy="12" r="'+(j===active?4.5:3)+'" fill="'+(j<=active?'#efaa6d':'#a2b4a3')+'"/><text x="'+x+'" y="35" text-anchor="'+(j===0?'start':j===2?'end':'middle')+'" fill="'+(j===active?'#fff4df':'#b9c8b9')+'" font-size="9" font-family="Inter,Arial" font-weight="700">'+a[j]+'</text>'}body+='<circle cx="'+(24+312*p)+'" cy="12" r="7" fill="none" stroke="#efaa6d" opacity="'+(.4+.25*Math.sin(t*3))+'"/></svg>';$('mechanism').innerHTML=body}
function render(t){t=Math.max(0,Math.min(duration,Number(t)||0));let n=0;scenes.forEach((s,i)=>{if(t>=s.t)n=i});if(n!==current){current=n;let s=scenes[n];$('headline').innerHTML=s.h;$('kicker').textContent=s.k;$('sub').textContent=s.sub;$('credit').textContent=s.src;document.querySelectorAll('.chapter').forEach((b,i)=>b.classList.toggle('active',i===n))}updateVisual(t,n);mechanism(t,n);let s=scenes[n],u=t-s.t,end=n+1<scenes.length?scenes[n+1].t:duration,vi=photoFor(t,n),shotStart=vi?(s.t+end)/2:s.t,shotDur=vi?(end-s.t)/2:(s.visuals.length>1?(end-s.t)/2:end-s.t),q=Math.max(0,Math.min(1,(t-shotStart)/shotDur));let im=document.querySelector('.ai-main,.photo-main');if(im){let isAI=im.classList.contains('ai-main');im.style.transform=isAI?'scale('+(1+.025*q)+') translateY('+(-q*2)+'px)':'translateY('+(-1.5+3*q)+'px)';}
let ease=1-Math.pow(1-Math.min(1,u/.4),5);['headline','kicker','sub'].forEach((id,j)=>{let z=1-Math.pow(1-Math.min(1,Math.max(0,u-j*.045)/.35),5);$(id).style.opacity=z;$(id).style.transform='translateY('+((1-z)*10)+'px)'});if(t===0){['headline','kicker','sub'].forEach(id=>{$(id).style.opacity=1;$(id).style.transform='none'})}$('seek').value=t;$('time').textContent=fmt(t)+' / '+fmt(duration)}
window.seek=render;window.render=render;window.state=t=>t.toFixed(5);window.ready=false;const loaded=scenes.flatMap(s=>s.visuals).map(v=>new Promise(resolve=>{let i=new Image();i.onload=()=>resolve(true);i.onerror=()=>resolve(false);i.src=v.image}));Promise.all([document.fonts.ready,...loaded]).then(x=>{window.ready=x.slice(1).every(Boolean);render(audio.currentTime||0)});
let raf=0;function tick(){render(audio.currentTime);if(!audio.paused)raf=requestAnimationFrame(tick)};$('play').onclick=async()=>{if(audio.paused){if(audio.ended)audio.currentTime=0;try{await audio.play()}catch(e){$('play').textContent='Tap to retry audio'}}else audio.pause()};audio.onplay=()=>{document.body.classList.remove('paused');$('play').textContent='Ⅱ Pause';cancelAnimationFrame(raf);tick()};audio.onpause=()=>{cancelAnimationFrame(raf);document.body.classList.add('paused');$('play').textContent=audio.ended?'↻ Replay':'▶ Play'};audio.ontimeupdate=()=>render(audio.currentTime);audio.onended=()=>{render(duration);$('play').textContent='↻ Replay';document.body.classList.add('paused')};$('seek').oninput=()=>{audio.currentTime=Number($('seek').value);render(audio.currentTime)};render(0);
'''.replace('__SCENES__',json.dumps(S,ensure_ascii=False)).replace('__DURATION__',str(D))
html=re.sub(r'<script>.*?</script>',lambda m:'<script>'+script+'</script>',html,flags=re.S)
p.write_text(html)
(R/'storyboard_repo.json').write_text(json.dumps([{k:v for k,v in s.items() if k not in ['visuals','art']} for s in S],ensure_ascii=False,indent=2))
print('Repo-aligned preview built:',D,'seconds')
